-- DROP TABLE IF EXISTS public."CATEGORIA";

CREATE TABLE IF NOT EXISTS public."CATEGORIA"
(
    "ID" serial PRIMARY KEY,
    "NOME" character varying(100) NOT NULL,
    "DESCRICAO" text,
    CONSTRAINT "CATEGORIA_nome_key" UNIQUE ("NOME")
);

ALTER TABLE IF EXISTS public."CATEGORIA"
    OWNER to postgres;


-- DROP TABLE IF EXISTS public."PRODUTO";

CREATE TABLE IF NOT EXISTS public."PRODUTO"
(
    "ID" serial PRIMARY KEY,
    "NOME" character varying(100) NOT NULL,
    "PRECO" numeric(10,2) NOT NULL,
    "DESCRICAO" text,
    "CATEGORIA_ID" integer,
    CONSTRAINT "PRODUTO_CATEGORIA_ID_fkey" FOREIGN KEY ("CATEGORIA_ID")
        REFERENCES public."CATEGORIA" ("ID")
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

ALTER TABLE IF EXISTS public."PRODUTO"
    OWNER to postgres;
